### ISSUE TITLE
Need your help in getting the datasets used in the code

### ISSUE THREAD

**Issue by hemantrao01** [houking-can/RDANER#1]
Hi Team,

while running the code I encountered the inclusion of a dataset that I dont have. 

Please help

**Comment by houking-can** [comment]
> Hi Team,
> 
> while running the code I encountered the inclusion of a dataset that I dont have.
> 
> Please help

The dataset is available now, you can find it in [data](https://github.com/houking-can/RDANER/tree/master/data) directory.
